name: Workflows

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ToxTests:
    runs-on: ubuntu-latest
    steps:
      - uses: Somerandomguy10111/devops/actions/basepy@main
      - uses: Somerandomguy10111/devops/actions/toxtests@main
  Dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: Somerandomguy10111/devops/actions/basepy@main
      - uses: Somerandomguy10111/devops/actions/deptry@main
